<?php

return [

    '@meta' => [

        'language' => 'Czech',
        'author' => 'Vit Habada',

        'date' => [
            'shortdays' => ['Po', 'Út', 'St', 'Čt', 'Pá', 'So', 'Ne'],
            'longdays' => ['Pondělí', 'Úterý', 'Středa', 'Čtvrtek', 'Pátek', 'Sobota', 'Neděle'],
            'shortmonths' => ['Led', 'Úno', 'Bře', 'Dub', 'Kvě', 'Čer', 'Čvc', 'Srp', 'Zář', 'Říj', 'Lis', 'Pro'],
            'longmonths' => ['Leden', 'Únor', 'Březen', 'Duben', 'Květen', 'Červen', 'Červenec', 'Srpen', 'Září', 'Říjen', 'Listopad', 'Prosinec']
        ]
    ],


    // Common
    'Authenticate' => 'Přihlásit se',
    'Welcome back!' => 'Vítejte zpět!',
    'Dashboard' => 'Nástěnka',
    'General' => 'Obecné',
    'Settings' => 'Nastavení',
    'Logout' => 'Odhlásit se',
    'Info' => 'Info',
    'Filter by name...' => 'Filtrovat podle jména...',
    'Save' => 'Uložit',
    'Delete' => 'Odstranit',
    'Cancel' => 'Zrušit',
    'Entry' => 'Záznam',
    'Entries' => 'Záznamy',
    'Field' => 'Pole',
    'Fields' => 'Pole',
    'Date' => 'Datum',
    'Latest' => 'Nejnovější',
    'Group' => 'Skupina',
    'No group' => 'Žádná skupina',
    'Modified' => 'Upraveno',
    'Today' => 'Dnes',
    'Info' => 'Info',
    'Language' => 'Jazyk',
    'System' => 'Systém',
    'Meta fields' => 'Meta',
    'Are you sure?' => 'Jste si jisti?',
    'Search...' => 'Hledat...',
    'Activity' => 'Aktivita',
    '%s logged in' => '%s se přihlásil.',

    // Login
    'Authenticate Please!' => 'Přihlašte se prosím!',
    'Welcome back!' => 'Vítejte zpět!',
    'Please login by using your auth credentials.' => 'Prosím přihlašte se pomocí svých údajů.',
    'Authenticate' => 'Přihlásit se',
    'Login failed' => 'Přihlášení se nezdařilo',

    // Accounts
    'Account' => 'Účet',
    'Accounts' => 'Účty',
    'Name' => 'Jméno',
    'Username' => 'Uživatelské jméno',
    'Email' => 'Email',
    'Password' => 'Heslo',
    'New Password' => 'Nové heslo',
    'Create account' => 'Vytvořit účet',
    'Leave the password field empty to keep your current password.' => 'Pro změnu hesla zadejte heslo nové.',
    'Edit account' => 'Upravit účet',
    'Edit account settings' => 'Změnit nastavení účtu',
    'Delete account' => 'Odstranit účet',
    'Account saved!' => 'Nastavení účtu uloženo',

    //Groups
    'Group' => 'Skupina',
    'Groups' => 'Skupiny',
    'Add group' => 'Přidat skupinu',
    'Access' => 'Přístup',
    'Manage account groups and permissions' => 'Spravovat skupiny a oprávnění',
    'Media root path' => 'Kořenová cesta pro média',

    // Addons
    'Addons' => 'Moduly',
    'No additional addons installed.' => 'Nejsou nainstalovány žádné přídavné moduly.',

    // Collections
    'Collections' => 'Kolekce',
    'Collection' => 'Kolekce',
    'Show entries' => 'Zobrazit záznamy',
    'Create new entry' => 'Vytořit nový záznam',
    'Create a collection' => 'Vytvořit novou kolekci',
    'Add collection' => 'Přidat kolekci',
    'Edit collection' => 'Upravit kolekci',
    'Delete collection' => 'Odstranit kolekci',
    'You don\'t have any collections created.' => 'Nejsou zde žádné kolekce.',
    'Save Collection' => 'Uložit kolekci',
    'Add entry' => 'Přidat záznam',
    'Edit entry' => 'Upravit záznam',
    'Delete entry' => 'Odstranit záznam',
    'It seems you don\'t have any fields created.' => 'Zdá se, že jste nevytvořili žadná pole.',
    'Goto entries' => 'Zobrazit záznamy',
    'Fields on entries list page' => 'Zobrazovaná pole v seznamu',
    'Order entries on list page' => 'Pořadí záznamů v seznamu',
    'created' => 'vytvořeno',
    'modified' => 'upraveno',
    'descending' => 'sestupně',
    'ascending' => 'vzestupně',
    'Collection removed' => 'Kolekce odstraněna',
    'Collection saved!' => 'Kolekce uložena!',
    'Entry removed' => 'Záznam odstraněn',
    'Entry saved!' => 'Záznam uložen!',

    // Mediamanager

    'Mediamanager' => 'Správce médií',
    'Bookmarks' => 'Záložky',
    'Folders' => 'Složky',
    'Folder' => 'Složka',
    'Files' => 'Soubory',
    'File' => 'Soubor',
    'Upload files' => 'Nahrát soubory',
    'Find files...' => 'Nají soubory...',
    'You have nothing bookmarked.' => 'Nemáte žádné záložky.',
    'Table mode' => 'Tabulka',
    'List mode' => 'Seznam',
    'Folders hidden via filter' => 'Složky skryté filterem',
    'Files hidden via filter' => 'Soubory kryté filterem',
    'All' => 'Vše',
    'Show files + directories' => 'Zobrazit soubory + složky',
    'Show only directories' => 'Zobrazit jen složky',
    'Show only files' => 'Zobrazit jen soubory',
    'Bookmark folder' => 'Přidat složku do záložek',
    'Rename folder' => 'Přejmenovat složku',
    'Delete folder' => 'Odstranit složku',
    'Bookmark file' => 'Přidat soubor do záložek',
    'Rename file' => 'Přejmenovat soubor',
    'Delete file' => 'Odstranit soubor',
    'Download file' => 'Stáhnout soubor',
    'Size' => 'Velikost',
    'Last modified' => 'Naposledy změněno',
    'This folder is empty.' => 'Tato složka ja prázdná.',
    'Save file' => 'Uložit soubor',
    'Close file' => 'Zavřít soubor',
    'Do you really want to remove %s ?' => 'Opravdu odstranit %s ?',
    'This file is not writable!' => 'Do tohoto souboru nelze zapisovat!',
    'Please enter new name:' => 'Zadejte nové jméno:',
    'Please enter name:' => 'Zadejte jméno:',
    '%s is already bookmarked.' => '%s již je v záložkách',
    '%s bookmarked.' => '%s přidáno do záložek.',
    'Do you really want to remove %s ?' => 'Opravdu odstranit %s ?',

    // Regions
    'Regions' => 'Regiony',
    'Region' => 'Region',
    'Add region' => 'Přidat region',
    'Create a region' => 'Vytvořit region',
    'Edit region' => 'Upravit region',
    'Delete region' => 'Odstranit region',
    'You don\'t have any regions created.' => 'Nevytvořili jste žádné regiony.',
    'Form' => 'Formulář',
    'Template' => 'Šablona',
    'Region fields' => 'Pole regionu',
    'Form fields' => 'Pole formuláře',
    'Manage form' => 'Spravovat formulář',
    'Done' => 'Hotovo',
    'This region has no fields yet.' => 'Tento region zatím nemá žádná pole.',
    'Add field' => 'Přidat pole',
    'Insert form field' => 'Vložit pole',
    'You have no fields added.' => 'Nepřidali jste žádná pole.',
    'Embed region snippet' => 'Vložit region',
    'Save Region' => 'Uložit region',
    'Region removed' => 'Region odstraněn',
    'Region saved!' => 'Region uložen!',

    // Backups
    'Backups' => 'Zálohy',
    'You don\'t have any backups created.' => 'Nemáte vytvoženy žádné zálohy.',
    'Create a new backup' => 'Vytvořit novou zálohu',
    'Backups are located here' => 'Zálohy jsou zde',
    'Download backup' => 'Stáhnout zálohu',
    'Delete backup' => 'Odstranit zálohu',
    'Creating backup...' => 'Zálohuji...',
    'Backup created' => 'Záloha vytvořena',
    'Backup deleted' => 'Záloha odstraněna',

    // Forms
    'Forms' => 'Formuláře',
    'Form' => 'Formulář',
    'Add form' => 'Přidat formulář',
    'Show all forms' => 'Zobrazit všechny formuláře',
    'Create a form' => 'Vytvořit formulář',
    'Edit form' => 'Upravit formulář',
    'Delete form' => 'Odstranit formulář',
    'You don\'t have any forms created.' => 'Nevytvořili jste žádné formuláře.',
    'Form' => 'Formulář',
    'Template' => 'Šablona',
    'Form fields' => 'Pole formuláře',
    'Form fields' => 'Pole formuláře',
    'Manage form' => 'Spravovat formulář',
    'Done' => 'Hotovo',
    'This form has no fields yet.' => 'Tento formulář nemá žádná pole.',
    'Add field' => 'Přidat pole',
    'Insert form field' => 'Vložit pole',
    'You have no fields added.' => 'Nemáte přidána žádná pole.',
    'Embed form snippet' => 'Vložit formulář',
    'Save form' => 'Uložit formulář',
    'Save form data' => 'Uložit data formuláře',
    'Form removed' => 'Formulář odstraněn',
    'Form saved!' => 'Formulář uložen!',
    'Email form data to this adress' => 'Data z formuláře na tuto adresu',
    'Leave the field empty if you don\'t want to recieve any form data via email.' => 'Ponechte toto pole prázdné, nechcete-li e-mailem dostávát data z formuláře.',
    'It is important to prefix the form fields with %s .' => 'Je důležité uvézt prefix polí %s .',

    //API Settings
    'You have no api token generated yet.' => 'Nemáte vygenerovaný žádný API klíč.',
    'Generate api token' => 'Vygenerovat API klíč',


    // Galleries
    'Galleries' => 'Galerie',
    'Gallery' => 'Galerie',
    'Add gallery' => 'Přidat galerii',
    'All galleries' => 'Přidat galerie',
    'Create groups to organize your galleries.' => 'Vytvořte skupiny pro organizaci galerií.',
    'Create new group' => 'Vytvořit novou skupinu',
    'Show all galleries' => 'Zobrazit všechny galerie',
    'Create a gallery' => 'Vytvořit galerii',
    'Edit gallery' => 'Upravit galerii',
    'Delete gallery' => 'Odstranit galerii',
    'You don\'t have any galleries created.' => 'Nemáte vytvořeny žádné galerie.',
    'Gallery' => 'Galerie',
    'Template' => 'Šablona',
    'Manage gallery' => 'Spravovat galerii',
    'Done' => 'Hotovo',
    'This gallery has no fields yet.' => 'Tato galerie nemá žádná pole.',
    'Add images to gallery' => 'Přidat obrázky do galerie',
    'Single image' => 'Obrázek',
    'Images from folder' => 'Obrázky ve složce',
    '%s image(s) imported' => '%s obrázků importováno',
    'Insert gallery field' => 'Vložit pole galerie',
    'You have no fields added.' => 'Nemáte přidána žádná pole.',
    'Embed gallery snippet' => 'Vložit galerii',
    'Save gallery' => 'Uložit galerii',
    'Save gallery data' => 'Uložit data galerie',
    'Gallery removed' => 'Galerie odstraněna',
    'Gallery saved!' => 'Galerie uložena!',
    'You don\'t have any images in this gallery.' => 'V této galerii nejsou žádné obrázky.'
];
